package com.iamashad.meraki.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a chat message entity stored in the Room database.
 *
 * @property id Unique ID of the message, auto-generated by Room.
 * @property message The actual message content (text).
 * @property role The role of the sender (e.g., "user", "assistant", etc.).
 * @property context Optional contextual tag to associate with the message.
 * @property userId The ID of the user this message belongs to.
 */
@Entity(
    tableName = "chat_messages",
    indices = [androidx.room.Index(value = ["userId"])] // Adds index for better query performance
)
data class ChatMessage(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // Auto-generated primary key
    val message: String,
    val role: String,
    val context: String? = null,
    val userId: String
)
