package com.iamashad.meraki.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Phase 4: Room entity persisting a compressed summary of one conversation session.
 *
 * Schema: `session_summaries`
 *
 * Stored after each session to build the long-term user profile that is injected
 * into subsequent conversations via [com.iamashad.meraki.utils.MemoryManager].
 *
 * @param sessionId       UUID that matches the session ID used in [EmotionLog].
 * @param date            Unix epoch ms — used for ordering and the LIMIT 14 query.
 * @param dominantEmotion Primary emotion key observed during this session
 *                        (e.g. "anxious", "sad", "neutral").
 * @param keyThemes       Comma-separated topics mentioned (e.g. "work,sleep,family").
 *                        Extracted from the AI-generated bullet summary.
 * @param helperPattern   What type of AI response was most effective this session
 *                        (e.g. "Reassurance", "Reflective listening", "Gentle guidance").
 * @param summaryText     Full 3-bullet summary generated by Gemini (temp=0.3):
 *                        • Key concerns: …
 *                        • Emotional pattern: …
 *                        • Helpful response type: …
 * @param tokenCount      Estimated token cost of [summaryText]; used to guard the
 *                        300-token USER_PROFILE_RESERVE budget in [ContextConfig].
 */
@Entity(tableName = "session_summaries")
data class SessionSummary(
    @PrimaryKey val sessionId: String,
    val date: Long = System.currentTimeMillis(),
    val dominantEmotion: String,
    val keyThemes: String,
    val helperPattern: String,
    val summaryText: String,
    val tokenCount: Int
)
